create database coffee_project;

use coffee_project;

#creating tables on mysql and importing their values from excel(csv.files)
create table Orders (Order_id varchar(20) primary key, Order_date date, Customer_id varchar(20), Product_id varchar(10), Quantity int, Customer_name varchar(40),
 Email varchar(50), Country varchar(30), Coffee_type varchar(15), Roast_type char, size decimal(2,1), Unit_price decimal(3,1), sales decimal(5,2));

#modified my sales column
alter table orders
modify column sales decimal(6,2);

select * from orders;

create table Customers (Customer_id varchar(20) primary key, Customer_name varchar(40), Email varchar(50), Phonenumber varchar(30), Address_line1 varchar(100),
 City varchar(30), Country varchar(30), Postcode varchar(15), Loyalty_card varchar(10));

select * FROM customers;

create table Products (Product_id varchar(20), Coffee_type varchar(15), Roast_type char, Size decimal(2,1), Unit_price decimal(3,1), Price_per_100g decimal(4,3),
 Profit decimal(4,3), Sales decimal(6,2));

#deleting an unwanted column
alter table products
drop column sales;

select * from products;

#revenue generated in each country
select distinct country, sum(quantity) as Quantity, sum(sales) as Revenue from orders
group by country
order by sum(sales) desc;

#Revenue generated by year
select distinct year(order_date), sum(sales) from orders
group by year(order_date)
order by sum(sales) desc;

#total sales and quantity for each coffee type
select distinct coffee_type, sum(quantity), sum(sales) from orders
group by coffee_type
order by sum(sales) desc;
  
  select sum(sales) from orders
  
  #no of customers with loyalty cards
  select count(customer_id) from customers
  where loyalty_card = "yes";
  
  #customers that never ordered
  select count(c.customer_id) from customers as c
  left join orders as o
  on c.customer_id=o.customer_id
  where o.order_id is null;
 
  #revenue generated by loyalty customers
select count(c.customer_id) as 'number of customers with loyalty card', sum(o.sales) as 'total revenue' from customers as c
inner join orders as o
on c.customer_id = o.customer_id 
where c.loyalty_card = 'yes';

#creating table with loyalty customer info
create table loyalty_customers (Customer_id varchar(20) primary key, Customer_name varchar(40), City varchar(30), Country varchar(30));

#inserting values from preexisting table
insert into loyalty_customers
 select customer_id, customer_name, city, country from customers
 where customer_id 
 in (select customer_id from customers where loyalty_card = 'yes');
 
 select * from loyalty_customers;
 
 #Creating Views in MYSQL: view is a virtual table created by queries. 
Create view Top10_Customers as
select distinct pd.Customer_id, pd.Customer_name, c.Country, count(*) as 'total orders', sum(sales) as 'total payment'  from purchase_details as pd
inner join Customers as c
on c.customer_id = pd.customer_id
group by customer_id
order by sum(sales) desc
limit 10;



#top 10 coffee by Quantity
select distinct Product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
group by product_id
order by sum(quantity) desc
limit 10;

#top 10 coffee by Sales
select distinct Product_id as Product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
group by product_id
order by sum(sales) desc
limit 10;

#top 10 coffee in United States by quantity
select distinct product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
where country = 'united states'
group by  product_id
order by sum(quantity) desc
limit 10;

#top 10 coffee in united states by revenue
select distinct product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
where country = 'united states'
group by  product_id
order by sum(sales) desc
limit 10;

#top 10 coffee in United Kingdom by quantity
select distinct product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
where country = 'united kingdom'
group by product_id
order by sum(quantity) desc
limit 10;

#top 10 coffee in United Kingdom by revenue
select distinct product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
where country = 'united kingdom'
group by product_id
order by sum(sales) desc
limit 10; 

#top 10 coffee in Ireland by quantity
select distinct product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
where country = 'Ireland'
group by product_id
order by sum(quantity) desc
limit 10; 

#top 10 coffee in Ireland by revenue
select distinct product_id, sum(quantity) as Quantity, sum(sales) as Sales from orders
where country = 'ireland'
group by product_id
order by sum(sales) desc
limit 10; 

 create view Purchase_Detail as 
 select
 o.product_id,
 o.coffee_type,
 o.customer_id,
 c.customer_name,
 o.unit_price,
 o.sales
 from orders as o
 inner join customers as c 
 on o.customer_id = c.customer_id
 order by product_id;
 
select count(*) from purchase_details where customer_name = "Marja Urion";

 select * from purchase_detail;
 
 rename table purchase_detail to purchase_details;
 
 drop view top10_customers;


select * from top10_customers;

select * from customers 
where customer_id = '66458-91190-YC';

select lower(customer_name) from customers;

#calculating correlation: not supported by mysql
select country, corr(unit_price, sales)
from orders
group by country;
